---
title: "DK DD 22 / BDT"
output:
  pdf_document: default
  html_notebook: default
---


```{r}
library(survey)
library(ipumsr)
```

* ACS 2016 1% sample
* Looking at KS Head of Household only for now
* IPUMS is embargoed data but sharing results and code should be fine



```{r}
# below copy pasted from IPUMS
ddi <- read_ipums_ddi("usa_00004.xml")
data <- read_ipums_micro(ddi)
```

```{r}
HOH <- subset(data, RELATE == 1) # KS and Head of Household
```

```{r}
KS <- subset(data, RELATE == 1 & STATEFIP == 22) # KS and Head of Household
ipums_design <- svydesign(~CLUSTER, weights = ~HHWT, strata = ~STRATA, data = KS, nest = TRUE, check.strata = FALSE)

```

Average HH income in KS

```{r}
svymean(~HHINCOME, ipums_design, na.rm=TRUE)
```


```{r}
KS$SPMSNAP <- ifelse(KS$SPMSNAP == 99999, NA, KS$SPMSNAP) 
svytable(~round(HHINCOME, -4) + round(SPMSNAP, -3), ipums_design)[1:15, 1:10]
```
## Test model

```{r}
m <- svyglm( I(SPMSNAP > 0) ~ I(HHINCOME/1000), design=ipums_design, subset = HHINCOME <= 25e3 )
```

## More complete:

```{r}
m2 <- svyglm( 
  I(SPMSNAP > 0) ~ I(HHINCOME/1000) + I(SEX==2) + I(AGE/10) + KITCHEN + I(OWNERSHPD == 22) +
    I(AGE >= 63) + # Social Security Age
    NCHILD +    NCHLT5 +
    I(CINETHH == 3) + # no internet
    I(MARST == 6) + #never marriend
    I(RACE != 1) + I(HISPAN != 0) + I(CITIZEN >= 3) + 
    I(SPEAKENG == 1) + # Does Not speak english
    I(HCOVANY == 1) + # No Health Insurance
    I(HINSCAID == 2) + I(HINSCARE == 2) + # Medicaid
    I(SCHOOL == 2 & GRADEATT >= 7) + #active college student
    I(EMPSTATD == 20) + #Unemployed +
    I(UHRSWORK / 40) + 
    I(VETSTAT == 2) + 
    I(TRANWORK == 10)  + # commute by own car
    I(SPMWIC / 1000) + 
    I(SPMEITC / 1000) + 
    I(SPMLUNCH / 1000)
  , 
  design=ipums_design, subset = HHINCOME <= 25e3, family=binomial() )

 options(scipen=2, digits=6)

summary(m2)
```

## SNAP vs School Lunch

```{r}
svytable(~round(SPMSNAP, -3)+round(SPMLUNCH, -3), ipums_design)
```
## SNAP vs WIC

```{r}
svytable(~round(SPMSNAP, -3)+round(SPMWIC, -3), ipums_design)
```

```{r}
HOH$snap_actual <- HOH$SPMSNAP > 0
HOH$snap_predict <- predict(m2, newdata=HOH, type="response")
HOH$low_income <- HOH$HHINCOME <= 25e3
hoh_design <- svydesign(~CLUSTER, weights = ~HHWT, strata = ~STRATA, data = HOH, nest = TRUE, check.strata = FALSE)


```


```{r}
system.time(
  res2 <- svyby(~snap_actual + snap_predict, ~snap_actual+STATEFIP, subset(hoh_design, HHINCOME <= 25e3), svytotal)
)
```


```{r}
require(USCensus2020state)
require(dplyr)
require(sf)

states_joined <- filter(res2, snap_actual) %>% 
  mutate(take_rt=snap_predict / snap_actualTRUE) %>% 
  mutate(GEOID20=sprintf("%02d", STATEFIP)) %>% 
  inner_join(x=states20) # NB put sf on left to retain classing correctly

```


```{r}
plot(states_joined[,"take_rt"], xlim=c(-100, -70))
```
```{r}
knitr::kable(xtable::xtable(m2))
```

## Effect of density on take

```{r}
summary(update(m2, .~.+poly(log10(DENSITY),3, raw=TRUE)))
curve(2.17*log10(x) + -1.039*log10(x)^2+.13*log10(x)^3, from = min(HOH$DENSITY), to=max(HOH$DENSITY))
```